### ISSUE TITLE
Replace betterbrief googlemapfield in v7.x ?

### ISSUE THREAD

**Issue by JamesDPC** [xini/silverstripe-social-metadata#12]
Hi folks

Looking at the diff: https://github.com/BetterBrief/silverstripe-googlemapfield/compare/master...xini:silverstripe-googlemapfield:master it would seem that `innoweb/silverstripe-googlemapfield` could replace `betterbrief/silverstripe-googlemapfield` without any work in v7.x (already replaced in 8.x) + as the framework requirements are `^4 || ^5`

Would this be possible ?

Thanks
James

**Comment by JamesDPC** [comment]
... and `innoweb/silverstripe-googlemapfield` could be marked as a replacement for the original:
https://getcomposer.org/doc/04-schema.md#replace

thanks

**Comment by xini** [comment]
Hi James,

Yes, absolutely. Done so in [7.3.0](https://github.com/xini/silverstripe-social-metadata/releases/tag/7.3.0).

Cheers
