### ISSUE TITLE
Config dot notation fails to retrieve map field API Key value

### ISSUE THREAD

**Issue by JamesDPC** [xini/silverstripe-social-metadata#13]
Hi

In https://github.com/xini/silverstripe-social-metadata/blob/master/src/Extensions/ConfigExtension.php#L515
The following returns null, even though the value is set in project yml config.

```php
$googleMapsFieldModuleAPIKey = Config::inst()->get(GoogleMapField::class, 'default_options.api_key');
if ($googleMapsFieldModuleAPIKey) {
    return $googleMapsFieldModuleAPIKey;
}

return null;
```

I set it to the below, and it was happier. I don't think dot notation works in Config :(

```php
$googleMapsFieldDefaultOptions = Config::inst()->get(GoogleMapField::class, 'default_options');
return $googleMapsFieldDefaultOptions['api_key'] ?? null;
```

Happy to do a PR but it's trivial fix if you are OK with updating?

Thanks
James

**Comment by xini** [comment]
Thanks. This is now fixed in 7.3.1 and 8.2.2
