### ISSUE TITLE
Site settings page crashes, multivaluefield not found

### ISSUE THREAD

**Issue by oosacker** [xini/silverstripe-social-metadata#14]
![Screenshot 2024-07-08 at 3 34 31 PM (1)](https://github.com/user-attachments/assets/bb44892a-a9bf-4702-9fc6-680d20ea6cca)

This only seems to happen on a local site with Silverstripe 5.0+. 

It is fixed by deleting `/vendor` and `/public/_resources/vendor` folders, then reinstalling all modules.

**Comment by xini** [comment]
Caching issue. Not related to this module.
