### ISSUE TITLE
Twitter Handle

### ISSUE THREAD

**Issue by spekulatius** [xini/silverstripe-social-metadata#2]
Hello @xini :wave: 

Thanks for this module. Super useful! I've installed the module and configured my Twitter handle in the settings. But it doesn't get added to the meta tags. I expected it as a "twitter:creator". Is there something I'm missing? Should it show up? Just keen to clarify - then I have a look and fix it.

Peter

**Comment by xini** [comment]
Hi Peter,
Sorry for this. This is now fixed in version 5.0.5, displaying the field in twitter:site. 
The content of twitter:creator is generated from the twitter handle field of the authoring member.
Cheers, Flo

**Comment by spekulatius** [comment]
Cool, thank you for fixing it. It's just a think I noticed. Again: Thanks
for making this module!

**Comment by xini** [comment]
No worries, you are welcome! ;)
