### ISSUE TITLE
New lines in description or not?

### ISSUE THREAD

**Issue by spekulatius** [xini/silverstripe-social-metadata#3]
Hello @xini 

maybe you could help me settle a question: Should there be new lines in the descriptions etc. or should it all be in one line ?

Background: I've noticed that some tags contain new links:

![image](https://user-images.githubusercontent.com/8433587/55135507-6b457300-515e-11e9-91a1-0ee7b302d85e.png)

its on this website: https://helloholidays.xyz

-- Peter

**Comment by xini** [comment]
Hi Peter,

Newlines in the meta description are ignored, see [here](https://stackoverflow.com/questions/6179889/google-meta-description-linebreak-possible). So it doesn't matter if they are there.

I usually use my [metacounter module](https://packagist.org/packages/innoweb/silverstripe-metacounter) to show the user how many characters are left for the description. It also prevents that newlines are entered in the field in the first place. 

Cheers

**Comment by spekulatius** [comment]
Hallo Florian

ah, okay. Thanks for resolving this. I'll add the mobile and avoid the issue completely.

Peter
