### ISSUE TITLE
og:image:alt support

### ISSUE THREAD

**Issue by spekulatius** [xini/silverstripe-social-metadata#4]
I've discovered Facebook supporting a `og:image:alt` parameter. Do you think its worth to add in? I could do it, just checking beforehand

**Comment by xini** [comment]
Hi Peter,
That's a good idea. Do you want to submit a PR?
Cheers

**Comment by spekulatius** [comment]
Sure, I'll prepare one shortly :+1:

**Comment by spekulatius** [comment]
Oh, I forgot about this. Sorry about that :/

**Comment by xini** [comment]
No worries ;)
