### ISSUE TITLE
REFACTOR use MetaComponents for setting MetaTags

### ISSUE THREAD

**Issue by muskie9** [xini/silverstripe-social-metadata#5]
Currently many modules utilize the `MetaTags` method to implement/override various Meta Tags, however this requires pattern recognition such as the [`title`](https://github.com/xini/silverstripe-social-metadata/blob/master/src/Extensions/SiteTreeExtension.php#L64) tag in this module. Utilizing the `MetaComponents` method, and assigning to the key => val array allows for easier management and replacement of values/tags as seen in [SiteTree](https://github.com/silverstripe/silverstripe-cms/blob/4/code/Model/SiteTree.php#L1400-L1403).

An example of this change is how the canonical tag is now generated for [`VirtualPage`](https://github.com/silverstripe/silverstripe-cms/pull/2647/files).

**Comment by xini** [comment]
Thanks, this sounds great, I never even noticed that method. I guess there are a lot of things slipped into new versions that don't get mentioned in the changelogs properly... 
I'll have a look into this when I have time. In the meantime, PRs welcome.
