### ISSUE TITLE
QUESTION should FeaturedImage take precedence over MetaImage on BlogPost?

### ISSUE THREAD

**Issue by muskie9** [xini/silverstripe-social-metadata#8]
Internally during a blog post review we noticed the image added to the Metadata tab was not being utilized in the page's og:image output. This was only the case if we did not include a Featured Image on the blog post. This is currently expected behavior based on the current logic. About a week later we had a client ask if that was expected behavior as the Featured Image is not necessarily optimized for social channels.

The underlying question here that we've been contemplating is whether a user would expect the image in the Metadata field to be used as the og:image if both fields have an image uploaded. It would make sense that the field present for that specific purpose would have preference over any existing image fields, and would fall back to those other fields if a MetaImage is not provided.

I'm not sure what the process would be for this type of change as it would break any existing installations if a change was made to the logic changing the field preference and fallbacks. As it stands currently, we're working through adjusting the image logic at the Page.php level, calling the parent method which will fire all extensions, then running logic to re-set the image if necessary for BlogPost pages.

**Comment by xini** [comment]
Hey Nic,
Thanks for raising this. I totally agree. The expected behaviour is as you described which warrants a bugfix rather than a minor or even major release.
Do you want to submit a PR or do you want me to have a look into this?
Cheers

**Comment by muskie9** [comment]
I can take a crack at making the update. I think it's just changing the order of operations in a couple spots if I read everything right.

I hope to submit it later today or tomorrow.

**Comment by xini** [comment]
Thanks!
